plugins {
    id 'com.android.application'
}
android {
    namespace 'com.tiao2.fastgithub'
    compileSdk 33
    defaultConfig {
        applicationId "com.tiao2.fastgithub"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'dnsjava:dnsjava:3.5.2'   // 降级到稳定版本
}